### ISSUE TITLE
suggestion for pvpgn

### ISSUE THREAD

**Issue by Danteoriginal** [pvpgn/pvpgn-server#149]
add simple antispoofer

https://github.com/Danteoriginal/pvpgn/commit/06ca4c22b3b9d0627980fad73eed7767a20fdce2
https://github.com/Danteoriginal/pvpgn/commit/05e270f421147dea4956020b51bbb23a134385aa

**Comment by HarpyWar** [comment]
You've created a pool request https://github.com/pvpgn/pvpgn-server/pull/162 with these commits. But actually your changes are incorrect.

- Text must be in English
- Code for checking non-exist account in connections is not correct (I could be wrong because I didn't test it)

Also I'm not sure should it be added in Lua scripts or hardcoded.
As far I understand it should be just a message for all ingame players that a player is connected from outside with bypass a server login.

**Comment by xboi209** [comment]
Yeah this looks like it just sends a message to everyone in the game. The server still can't tell if the user is a spoofer or not, nor can it prevent the spoofing. SID_READMEMORY or SID_EXTRAWORK should be used for hack detection.
