### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by xvids** [pvpgn/pvpgn-server#159]
Plz help http://forums.harpywar.com/viewtopic.php?pid=7184

length (got 166 bytes, hack attempt?)
Jun 15 11:03:10 [error] handle_bnet_packet: [22] (logged in) got error handling packet type 0x1cff, len 166
Jun 15 11:03:13 [error] _client_startgame4: [22] got abnormal STARTGAME4 packet length (got 166 bytes, hack attempt?)
Jun 15 11:03:13 [error] handle_bnet_packet: [22] (logged in) got error handling packet type 0x1cff, len 166
Jun 15 11:03:16 [error] _client_startgame4: [22] got abnormal STARTGAME4 packet length (got 166 bytes, hack attempt?)
Jun 15 11:03:16 [error] handle_bnet_packet: [22] (logged in) got error handling packet type 0x1cff, len 166
Jun 15 11:03:19 [error] _client_startgame4: [22] got abnormal STARTGAME4 packet length (got 166 bytes, hack attempt?)
Jun 15 11:03:19 [error] handle_bnet_packet: [22] (logged in) got error handling packet type 0x1cff, len 166
Jun 15

Jun 15 11:38:49 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:38:56 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:39:11 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:40:02 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:40:25 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:41:13 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:42:24 [error] game_set_status: attempting to set status 'open' (2) to started game
Jun 15 11:43:28 [error] game_set_status: attempting to set status 'open' (2) to started game

**Comment by xboi209** [comment]
Write steps on how to reproduce the error

**Comment by xvids** [comment]
Login to the bot(Ghost one) to finish -> error.

ip: war3.hackforums.ru (bots: [hf] life, [hf] life 2)

**Comment by xvids** [comment]
on other servers everything is fine (iP: rubattle.net)
ghost one https://code.google.com/p/ghost1/downloads/list

**Comment by xvids** [comment]
I try to roll back to: https://github.com/HarpyWar/pvpgn/releases if you do not forget write

**Comment by xboi209** [comment]
This isn't a problem with PvPGN, the bot is incorrectly sending packets

**Comment by xvids** [comment]
166 bytes -.-

**Comment by xboi209** [comment]
Disable the if statement at line 4058

**Comment by xvids** [comment]
thx

how to fix? game_set_status: attempting to set status 'open' (2) to started game

**Comment by xboi209** [comment]
That's an issue with the bot, it's trying to set the game status as open when the game already started. You can't join started games so the status shouldn't be set as open.

**Comment by HarpyWar** [comment]
@xboi209  As you can see below that code - each gamename, gamepass, gameinfo are correctly checked  for max length separately.
Despite the fact that STARTGAME4 packet's maximum size is 216 bytes, Starcraft client crashes when length of the packet > 160. Create a game with this packet length can not be reproduced in Starcraft, I tried it with a self-made bot program 6 years ago.
It happens  because mapname is at the end of the packet, and when packet size is greater 160 then stack overflow occurs and a game crashes. It's a bug in Starcraft client.

I'm not sure that I've done it right, but for now I add check for Starcraft client only, so a log line with abnormal packet length will not appear again with other game clients.
