### ISSUE TITLE
C&C Renegade (WOL) Crashes

### ISSUE THREAD

**Issue by Sora012** [pvpgn/pvpgn-server#197]
Installed a fresh copy of PvPGN 1.99 (SVN) on both Windows & Linux.. Redirected servserv.westwood.com to my servers IP . Installed a fresh copy of Renegade & Launch Renegade, sign in. MOTD shows up, and then "Renegade has stopped working".

Renegade's _except.log says:
Error code: EXCEPTION_ACCESS_VIOLATION
Description: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Access address:00000000 was read from.
Exception occurred at 0078EECE

bnetd.log says:
Mar 28 12:49:23 [info ] conn_create: [9][-1] sessionkey=0x32c5e851 sessionnum=0x00000001
Mar 28 12:49:23 [debug] sd_accept: [9] client connected to a wolv2 listening address
Mar 28 12:49:23 [debug] handle_irc_common_line: [9] got "" "LISTSEARCH" ["16780288" "-1" "0" "0" "0"] "sora:"
Mar 28 12:49:23 [debug] handle_irc_common_set_class: Got WOL Ladder packet
Mar 28 12:49:23 [debug] _ladder_send: [9] sent "

NOTFOUND
"
Mar 28 12:49:23 [info ] conn_destroy: [9] closed wladder connection
Mar 28 12:49:29 [debug] sd_tcpinput: [8] read returned -1 (closing connection)
Mar 28 12:49:29 [info ] conn_destroy: [8] "Sora" logged out

**Comment by Sora93** [comment]
If you comment out the following line:
https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L1715

C&C Renegade stops crashing on connection to WOL.

**Comment by Sora93** [comment]
Also would like to point out that the gamelist for Renegade shows absoluetely nothing when multiple games are create it says "not listing because game is not open" in the bnetd.log even though the game has no password.

**Comment by xboi209** [comment]
I'm unable to help because I'm not familiar with the Westwood online protocol and the game.

**Comment by Sora93** [comment]
SVN 1.99-521 has a working Renegade if you wanna look at that release..

Current release log file:
Apr 01 03:16:35 [debug] channel_create: creating new channel "AGC" shortname="AGC" clienttag=(none) country=(none) realm=(none)
Apr 01 03:16:35 [debug] channel_create: channel was not added into any channellist
Apr 01 03:16:35 [debug] channel_create: channel created successfully

I think the "channel was not added into any channellist" is the main reason that renegade has no game lobbies for the dedicated server or for clients. The SVN 1.99-521 release also said "(none)" as a client tag so I think that isn't the issue..

**Comment by xboi209** [comment]
If you can find the exact commit in which Renegade begins to crash, I _might_ be able to help. Otherwise, I currently don't have the interest in investing time to find the problem in the code.

**Comment by Sora93** [comment]
I know its been a long time. However I narrowed it down to: pvpgn-199.r521 as the last build that was working.

However this build DOES NOT list game settings properly. It DOES list the server, and it is playable.

Log File (Expires in a Month)
https://pastebin.com/hQM7HvaN

**Comment by RElesgoe** [comment]
r521 seems to have been released on December 17, 2008. Could you try to build and test the commits after that date?
https://github.com/d1zzy/pvpgn/commits/master?after=69976febd2347eb9a92cefd9b853d45c8e6663ff+34

**Comment by Sora93** [comment]
https://github.com/d1zzy/pvpgn/commit/527d917bd94a0272743a82b2f88d91919c8087e6
This build works 100% (Minus a crash if you try to sort the list by dedicated or favorites)
Any of the other builds crash like previous on login, which is related to the ladder code.

I'll comment out the ladder code in the builds and continue testing against newer releases to see at what point the game stopped listing its sessions.

**Comment by RElesgoe** [comment]
Try testing https://github.com/d1zzy/pvpgn/commit/97353e39df44fe65511dc908ccebe7956092542f and https://github.com/d1zzy/pvpgn/commit/a6825c01a590802209bb7a81fa66da98140ca9d3

**Comment by Sora93** [comment]
I tested https://github.com/d1zzy/pvpgn/commit/97353e39df44fe65511dc908ccebe7956092542f
It works! the only issue is I had to comment out this if statement
https://github.com/d1zzy/pvpgn/blob/97353e39df44fe65511dc908ccebe7956092542f/pvpgn/src/bnetd/handle_wol.cpp#L472
One you comment out that "if" statement it lists the server, the buddy system says they are in a game lobby, and are capable of playing.

**Comment by RElesgoe** [comment]
What about the other commit?

**Comment by Sora93** [comment]
Both commits require altering code to actually get to work, I think when I wrote that other comment, I was running another version.. Sorry.

However! I did find the source of the crash its the "\r\n" on the "NOTFOUND\r\n"
https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L1717
Simply removing "\r\n" renegade stops crashing on login, and is capable of viewing the server list.
The only remaining issue is, that the game refuses to list servers.

https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L467
This IF statement, if you disable it, it lists the servers BUT! You cannot join. You receive "Game channel closed" if you disable -that- statement, it will prompt you "You're banned from this channel" and the log reports something about checking channel "NULL"

**Comment by RElesgoe** [comment]
Is a server a synonym for a game in WOL?

**Comment by Sora93** [comment]
Yes. Its called it the "Renegade Free Dedicated Server". In game, it has a icon for "Dedicated Server". So I short hand it as "server". Sorry for any confusion.

**Comment by Sora93** [comment]
I made a bit of progress with the listing games part, The PvPGN Server would spit out "not listing game" and I had to originally disable this statement https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L467 BUT! If you add a check for C&C Renegade 

`if ((conn_get_clienttag(conn) == CLIENTTAG_RENEGADE_UINT) || (conn_get_clienttag(conn) == CLIENTTAG_RENGDFDS_UINT)) { game_set_status(game, game_status_open); } else { game_set_status(game, game_status_started); }`

at this location https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L1329
The game will then begin listing game sessions! game_status_started, would normally apply to other WOL titles such as Red Alert 2, but Renegade doesn't support the "game_status_started" because then if any "gameserver" lists itself, its "started" as soon as the host starts the session or dedicated server starts

Now, the only remaining issue, that I cannot seem to pinpoint or figure out is unable to join the game server, PvPGN Server will issue the following:

May 21 19:25:42 [debug] _handle_list_command: [** WOL **] LIST [Game]
May 21 19:25:42 [debug] irc_send_cmd: [24] sent ":Sora-PC.lan 326 Sora #AGSora 1 4 12 0 0 2130706433 128::G24T4F453BA30B1060BA000000000000000022" 9Dedicated Renegade Server0C&C_City_Flying.00FFFFFFFFFFFFFF"
May 21 19:25:42 [debug] _handle_list_command: [24] LIST sent 1 of 1 games
May 21 19:25:42 [debug] irc_send_cmd: [24] sent ":Sora-PC.lan 323 Sora :End of LIST command"
May 21 19:25:44 [debug] handle_irc_common_line: [24] got "" "JOINGAME" ["#AGSora" "1"] ""
May 21 19:25:44 [debug] irc_send_cmd: [24] sent ":Sora-PC.lan 478 Sora #AGSora :Game channel has closed"

**Comment by Sora012** [comment]
Simplest fix for Renegade crashing at login is at line 1714 in handle_wol.cpp

https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_wol.cpp#L1714

remove "\n" as far as i can tell with Red Alert 2 this has no side effects. It might affect other games. so condition check for renegade client tag / renegade fds client tag should fix this;
