### ISSUE TITLE
Create versioncheck entry for WarCraft 3 1.27B

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#266]

**Comment by cen1** [comment]
Will prep a pull request tomorrow. Stop me if someone is already on it.

**Comment by cen1** [comment]
This is what I got so far:
```
# Warcraft III - TFT (Expansion) 1.27b
# Note: this version check is sent in both TFT and ROC mode
"B=454282227 C=2370009462 A=2264812340 4 A=A^S B=B-C C=C-A A=A+B" \
 ver-IX86-1.mpq \
 IX86 \
 W3XP \
 "War3.exe 12/09/16 06:05:09 515048" \
 0x0000001b \
 1.27.1.173 \
 0x4026b5b0 \
 W3XP_127B
 
# Warcraft III - ROC 1.27b
# Note: this version check is sent in both TFT and ROC mode
"B=454282227 C=2370009462 A=2264812340 4 A=A^S B=B-C C=C-A A=A+B" \
 ver-IX86-1.mpq \
 IX86 \
 WAR3 \
 "War3.exe 12/09/16 06:05:09 515048" \
 0x0000001b \
 1.27.1.173 \
 0x4026b5b0 \
 WAR3_127B
```

First two lines are copied from 1.27a, I am not certain about the procedure. Checksum is copied from PvPGN log when trying to connect to it. I was unable to find the source of the checksum in bnet packet capture so I am not sure it is correct.
I was able to connect via ghost and latest bncsutil with this config. I am not yet able to test with w3 client since we are waiting for w3l to be updated.

We should also document the procedure about adding new entries in some wiki or a readme so the steps are known in advance.

**Comment by cen1** [comment]
The above config confirmed working with w3l for 1.27b. Will test more on the weekend and prepare a pull.

**Comment by XanderGS** [comment]
Great, please confirm if everything is good to go, @cen1 . Thanks
