### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by hagiali** [pvpgn/pvpgn-server#291]
First, i can't connect to your forum, email registration method fail because confirmation email is never send , and the auth via facebook or gmail end with a SQL error.

UPDATE:
I installated this build 'pvpgn-master-d594199_mysql' 
the problem is when i connect from 1.27b, the password is correct, but the pvpgn server tell is wrong. with 1.26 all good.

**Comment by hagiali** [comment]
logs from  1.27b
```
Mar 08 20:51:53 [trace] pvpgn::bnetd::sql_read_account: SELECT uid FROM pvpgn_BNET WHERE username='hagiali'
Mar 08 20:51:53 [trace] pvpgn::bnetd::sql_read_attrs: SELECT * FROM pvpgn_BNET WHERE uid='3'
Mar 08 20:51:53 [info ] pvpgn::bnetd::_client_loginreqw3: [840] (W3) "hagiali" passed account check
Mar 08 20:51:53 [info ] pvpgn::bnetd::_client_logonproofreq: [840] logon proof requested
Mar 08 20:51:53 [info ] pvpgn::bnetd::_client_logonproofreq: [840] (W3) got wrong client password proof for "hagiali"
```
logs from  1.26
```
Mar 08 20:55:10 [trace] pvpgn::bnetd::sql_read_account: SELECT uid FROM pvpgn_BNET WHERE username='hagiali'
Mar 08 20:55:10 [trace] pvpgn::bnetd::sql_read_attrs: SELECT * FROM pvpgn_BNET WHERE uid='3'
Mar 08 20:55:10 [info ] pvpgn::bnetd::_client_loginreqw3: [552] (W3) "hagiali" passed account check
Mar 08 20:55:10 [info ] pvpgn::bnetd::_client_logonproofreq: [552] logon proof requested
Mar 08 20:55:10 [trace] pvpgn::bnetd::sql_read_attrs: SELECT * FROM pvpgn_friend WHERE uid='3'
Mar 08 20:55:10 [trace] pvpgn::bnetd::sql_read_attrs: SELECT * FROM pvpgn_friend WHERE uid='0'
Mar 08 20:55:10 [info ] pvpgn::bnetd::_client_logonproofreq: [552] (W3) "hagiali" logged in (right password)
```

**Comment by cen1** [comment]
Are you using w3l?

**Comment by hagiali** [comment]
yes cen

**Comment by HarpyWar** [comment]
The similar issue was described [on forums](https://forums.pvpgn.pro/viewtopic.php?id=1693) by r00t. He said that he switched from PvPGN 1.99 to PRO version and existing users periodically can't connect to a server with wrong password. 

What I did find out from him:
1) Passhash in a database is set to `67452301efcdab8998badcfe10325476c3d2e1f0` **sometimes** and only for a new registered accounts. As you can see this hash is default for new accounts in `bnetd_default_user.plain`
```
"BNET\\acct\\passhash1"="67452301efcdab8998badcfe10325476c3d2e1f0"
```
2) For old (existing) accounts passhash not changed. But **several** users **always** can't connect with previous password, while others **always** can. It means there are no cases when a user can connect a hour ago and not can't, and vice versa.
3) He (server owner) can connect to the server with old accounts (using passwords cracked from hashes on http://harpywar.pvpgn.pl) with which that users can't connect, with the same passwords. 
4) When he switch back to version 1.99, all users who could not connect with old accounts - get again this ability. But, of course, not on new accounts that has a passhash `67452301efcdab8998badcfe10325476c3d2e1f0 `.

I though the problem may be in a local client `bncache.dat`, but more likely it's in different loader as @hagiali wrote. But the server owner is sure that all users use this one [w3l.exe](http://forums.pvpgn.pro/uploads/files/2017/01/19/w3l.zip).
I could reproduce the issue with SRP loader, because PvPGN not uses a field `acct_passhash1` in this mode and set default hash there. Other fields uses instead: `acct_verifier` and `acct_salt`.
Or may be the problem is in PvPGN code, because it doesn't exist in 1.99 where all works fine. (I wrote to @RElesgoe about this possible bug two months ago.)

Someone should dig deeper into the code with sort of testing to find the problem place.

**Comment by HarpyWar** [comment]
@hagiali give me your email or username and SQL error text which you see when you're trying to register on https://forums.pvpgn.pro

**Comment by hagiali** [comment]
back, i sent u a print with errors. 

i have a completly new pvpgn server and i use only to test some maps, is first installation, with clean DB. i will try with ur loader. i hope is commpatible with all old pvpgn server (like cen, he is no1 )

**Comment by hagiali** [comment]
your w3l is old http://prntscr.com/ektvag
still can't connect

**Comment by hagiali** [comment]
WORK WITH https://github.com/w3lh/w3l
