### ISSUE TITLE
HWID ban

### ISSUE THREAD

**Issue by StevenFredette** [pvpgn/pvpgn-server#355]
IPbanning is worthless, since we can read memory with extra data we can grab pc username and hostname to make the banning more sophisticated? Let me know your thoughts.

**Comment by RElesgoe** [comment]
This is easy to circumvent and would also invade the privacy of the users.

**Comment by cen1** [comment]
You can probably do it with ExtraWork if you really wanted to.

**Comment by StevenFredette** [comment]
@cen1

I'll study extrawork does it write also and not just read?

**Comment by cen1** [comment]
It's a dll, it can do whatever afaik

**Comment by StevenFredette** [comment]
@cen1

Not sure this extrawork works with Warcraft 2 I'm sad now. :(

**Comment by RElesgoe** [comment]
You can use [CheckRevision](https://github.com/pvpgn/CheckRevision)

**Comment by StevenFredette** [comment]
Ill research and see what I can learn with it.

**Comment by Kelly32** [comment]
Would love to see such feature and I don't think it would invade the privacy of users, it's the same thing as having a command to display their ip address. @StevenFredette is right and ip ban is worthless today because most are dynamic ip, vpn usage and more that's why other gameservers use HWID ban and it can be bypassed but takes more knowledge and most trolls that like to ruin the fun of others and keep coming back after a ban don't have that knowledge. If anyone ever finds a solution for HWID ban hope he can post it.

**Comment by RElesgoe** [comment]
Many people have their real name in their Windows username and PC name, while an IP address doesn't identify a user nor gives a precise location.
