### ISSUE TITLE
Bug when using any bot software

### ISSUE THREAD

**Issue by Kellsya** [pvpgn/pvpgn-server#356]
Having an issue while connecting using chat clients like stealthbot or topazchat. When I connect with stealthbot it shows 0 users inside of the channel even though there are users connected and in topazchat I am unable to type anything into the channel or join a different channel other than default one `Chat` (shomehow `Join a channel` option is grayed out) but I can see users in channel here. I tested at the same time on a clean pvpgn version 1.8.5/ 1.99 and everything seems to be fine there. I have added an image to see the member list is empty in stealthbot while being in the same channel.
Any ideas @RElesgoe? Maybe I'm missing some setting? Thanks

![git1](https://user-images.githubusercontent.com/1735513/40274314-3e4e5196-5bdc-11e8-9524-8f92439c0c07.png)

**Comment by RElesgoe** [comment]
Does this only occur when emulating the CHAT client?

**Comment by Kelly32** [comment]
Yes, when using any of the chat clients like stealthbot, topaz, mirage and so on.
Connecting another account with a game client like warcraft3, diablo2 I am able to see all both normal users connected through game clients and users connected with the chat software just fine inside of the channel, but only if using a game client.

**Comment by RElesgoe** [comment]
So to clarify, when using a bot software like Stealth other, this problem only occurs when emulating the CHAT client, but doesn't occur when emulating Diablo 2 or other games?

**Comment by Kelly32** [comment]
Happens when emulating any client, including CHAT. In the first image `testchat3` is emulating CHAT client through topazchat, `testchat2` is a normal user connected with diablo2 client and `testchat1` is emulating D2XP client. I also then used `testchat` to emulate W3XP client and same result. So as long as you a bot software like stealthbot you will experience this bug while emulating either CHAT or ANY other games.

**Comment by RazorMid** [comment]
I registered after seeing this issue to confirm that I get the same bug, vert annoying for one who uses a chat bot. Wonder if any solutions have been found so far, please share.

**Comment by RElesgoe** [comment]
Can you guys confirm if [Stealthbot Build 491](https://github.com/stealthbot/StealthBot/releases/tag/v2.7-dev491) also has this issue?

**Comment by Kelly32** [comment]
@RElesgoe, can't even properly run that version. In win 2k8 throws run-time error 374 when trying to edit any bot settings and local hashing error fails. In windows7 I can start the bot but same local hasing error remains:
> [BNCS] Warning! The server signature is invalid. This may not be a valid server.
[BNCS] Local hashing failed.
All connections closed.

I tried to get [this plugin](http://www.stealthbot.net/forum/index.php?showtopic=1026) so it uses plain password but same local hashing failed. The issue can't be caused by stealthbot because same happens with topaz and any chat bot.

**Comment by RElesgoe** [comment]
Try using BNLS `bnls.bnetdocs.org` instead of local hashing.

I've tested Stealthbot build 482 and build 491 on Windows 10 and I am unable to reproduce this problem.

**Comment by Kelly32** [comment]
I use the Latest commit 36f9925 on May 9

Problem found in `channel.conf` I think.
After I change `--special name--` from `NONE` to `"Diablo II"` for D2DV and D2XP I can see users fine in all channels such as W3, Brood War and so on. 
This is default channel.conf config where stealthbot does not work https://pastebin.com/hcekQPqD
This is edited channel.conf config where stealthbot works https://pastebin.com/kUrda8yg

Topazchat still has problems though, doesn't let me choose channel or type anything and moves me to Chat channel no matter if I choose a different default channel. It works fine in 1.85 and 1.99

**Comment by Kelly32** [comment]
@RElesgoe, were you able to see what's wrong? Thanks

**Comment by RElesgoe** [comment]
I'm still having trouble recreating this problem.

**Comment by Kelly32** [comment]
This is so unfortunate because I want to start using pro version but need to correct this first. Can you tell me on what revision you test or upload config files including channel.conf? Or it's all default from revision 36f9925?

**Comment by RElesgoe** [comment]
I used the [1.99.7.2.0 release](https://github.com/pvpgn/pvpgn-server/releases/tag/1.99.7.2.0)(which is equivalent to 36f99253577487fdcf803183de29f70ff034c45e) and I'm running Stealthbot 2.7 Build 491.
