### ISSUE TITLE
D2CS crashes

### ISSUE THREAD

**Issue by Invicta76** [pvpgn/pvpgn-server#370]
Using the latest stable build of pvpgn pro and I've been experiencing the following issue, d2cs simply crashes multiple times in a row with the following error in d2cs.log [fatal] pvpgn::xrealloc_real: out of memory (from c:\pvpgn\source\src\common\queue.cpp:128) kicking all the players out of their diablo games then it stops crashing. This is the only log line showing the error and so far seems to be totally random, it could happen just once or several times in a row like every two minutes or so then it gets back to normal. Haven't found any .dmp that I can upload. It did happend on 1.99 too by the way and I've expected it to be a bug of that version, I've seen the same error inside the pvpgn forums too several times but it never got answered.
I am running the exact same setup for several years on a Win2k8 r2 dedicated and it rarely used to happen like once in months or so before. The server does have enough ram when the crash happens, literally the entire RAM is available on the machine. Any idea what's going on with that line in queue.cpp and how we can find more about this to get it fixed or prevent the crash ? Looks like a memory leak https://github.com/pvpgn/pvpgn-server/blob/master/src/common/queue.cpp
Thanks

**Comment by cen1** [comment]
There should be a .core dump file. If not, can you run in gdb to poinpoint the problem?

**Comment by Invicta76** [comment]
It should be generated in the /pvpgn root folder right? If yes, there's no such file then. Should I compile everything in debug mode or just strictly d2cs? The crash only happens for d2cs while d2dbs and pvpgn processes are fine. Haven't found any useful log lines inside the pvpgn.log either, the fatal error pops just in the d2cs.log

**Comment by cen1** [comment]
Looks like buffer overflow and out of memory is probably not the true error. Did you get to see the exact line where the error was thrown?

I am not sure if dump files are safe to share in public. Maybe pass protect it as zip just in case and send password via discord/email.

**Comment by Invicta76** [comment]
Those are the only errors I got, no line being mentioned in the popup window. Clicking abort, retry, ignore will simply close the popup window and the application. The only line generated during the crash is the one I've mentioned inside d2cs.log [fatal] pvpgn::xrealloc_real: out of memory (from c:\pvpgn\source\src\common\queue.cpp:128
I've sent the dump to harpy in a the pvpgn forums, hopefully that will help.

**Comment by Invicta76** [comment]
I've used both the gui and console version, @HarpyWar. My page file size was 4GB on a 32GB RAM PC with SSD. I've made a script that frees the cached ram and increased the page file size too and seems it's been stable for a while now. I think one of the two was causing the issue.

**Comment by HarpyWar** [comment]
The issue was not solved. Summarize from @Invicta76:
- It exists in 1.8.5
- The more players online the more often crashes occur (~500 online last time)
- There are enough memory on the server and it was tested on different server machines (only Windows?)
- He tried to increase `QUEUE_QUANTUM` to 100 without a success

`QUEUE_QUANTUM` is just count of packets to resize the queue in one moment if it is full, and it does not matter 10 or 100. But large value like 10000 may "fix" the issue, because it will allocate chunk of memory for a long period without the need for resize (realloc).

I have no idea why realloc function may fail in your case. I didn't write d2cs and it may require additional debugging by someone. 
Properly generated dump file may help find source of the problem. You can try create it manually, when the abort error message appears. Dont close the error window, go to to the Task Manager > right click on the process > Create Dump File
`d2cs.exe` should be compiled with debug symbols, so dont forget attach `d2cs.pdb` (or `d2csconsole.pdb` if use console version). It can be compiled with Magic Builder by running `rebuild_pvpgn_debug.bat` which should be created after first release build.
