### ISSUE TITLE
Hello, I have bug in commands!

### ISSUE THREAD

**Issue by Slipknotivo2** [pvpgn/pvpgn-server#413]
Hello! I compile new release in ubuntu 20!

This have Bug in command, example:

this command is "Finger"

€œ§ÝûU
Login: Lays01 94 
Created: Thu Mar 07 21:00 2019
Location: unknown 
€œ§ÝûUxxx.xx.xxx.xx

Email: 
Ðy¨ÝûU

Example Command /ANN

Type /ann hola

às¨ÝûU

All Command have bug

Thanks for help!

**Comment by HarpyWar** [comment]
Which git branch do you use, a game client and it's locale?
Try switch language with `/lang enUS` to check if the problem gone.

**Comment by Slipknotivo2** [comment]
no work language enUS, this release not folder enUS, change language /lan esES and work!

**Comment by HarpyWar** [comment]
`enUS` is default language. Enter `/lang` without a parameter to see list of available language codes.
With which language code do you see that bug?

**Comment by Slipknotivo2** [comment]
enUS only language bug

**Comment by Slipknotivo2** [comment]
sorry, i no closed! bad click!

**Comment by Slipknotivo2** [comment]
enUS only language bug, sorry i no closed, bad click!

**Comment by HarpyWar** [comment]
I confirm the issue on `master` branch, but with different behaviour. At least finger data is displayed incomplete.

![WC3ScrnShot_070820_104524_01](https://user-images.githubusercontent.com/1132835/86894291-86e24c00-c10b-11ea-8552-a96c2604ff96.png)


But it's ok in `develop` branch, so you can use it

![WC3ScrnShot_070820_104619_02](https://user-images.githubusercontent.com/1132835/86894299-8944a600-c10b-11ea-84da-7efc961084be.png)


May be the nature of the issue is similar to https://github.com/pvpgn/pvpgn-server/issues/408
