### ISSUE TITLE
Server crashes on Warcraft III client connect

### ISSUE THREAD

**Issue by bmunger** [pvpgn/pvpgn-server#423]
Server shows the following error:
Oct 14 17:25:20 [info ] _client_logonproofreq: [24] (W3) "Zorix" logged in (right password)
Oct 14 17:25:20 [debug] _client_anongame_infos: client_tag request tagid=(0x0) tag=(CLIENT_FINDANONGAME_INFOTAG_URL)  tag_unk=(0x0000)
Oct 14 17:25:20 [debug] _client_anongame_infos: client_tag request tagid=(0x1) tag=(CLIENT_FINDANONGAME_INFOTAG_MAP)  tag_unk=(0x0000)
Oct 14 17:25:20 [debug] _client_anongame_infos: client_tag request tagid=(0x2) tag=(CLIENT_FINDANONGAME_INFOTAG_TYPE) tag_unk=(0x0000)
Oct 14 17:25:20 [debug] _client_anongame_infos: client_tag request tagid=(0x3) tag=(CLIENT_FINDANONGAME_INFOTAG_DESC) tag_unk=(0x0000)
Oct 14 17:25:20 [debug] _client_anongame_infos: client_tag request tagid=(0x4) tag=(CLIENT_FINDANONGAME_INFOTAG_LADR) tag_unk=(0x0000)
Oct 14 17:25:24 [trace] _client_motdw3: lastnews() 1396087566 news_time 0
FATAL ERROR: argument index out of range

Client version is: 1.27.1.173
Server: 1.99.7.2.1-PRO (git master as of yesterday)

Works with Starcraft perfectly.  Let me know how else I can provide useful information.

**Comment by RElesgoe** [comment]
Can you try compiling from the `develop` branch.

**Comment by d333s** [comment]
I have the same issue. To elaborate a bit: This happens (for me atleast) only when the pvpgn is on a VPS on Ubuntu, this doesnt happen on the windows build. Also, it is impossible (for me atleast) to try the develop branch, since it errors. `/home/ubuntu/pvpgn-server/src/bnetd/topic.cpp:85:67:   required from here
/usr/include/c++/5/bits/stl_pair.h:145:64: error: call of overloaded ‘basic_string(nlohmann::basic_json<>&)’ is ambiguous
  : first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
                                                                ^
In file included from /usr/include/c++/5/string:52:0,
                 from /home/ubuntu/pvpgn-server/src/bnetd/topic.h:20,
                 from /home/ubuntu/pvpgn-server/src/bnetd/topic.cpp:18:
/usr/include/c++/5/bits/basic_string.h:476:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(basic_string&& __str) noexcept
       ^
/usr/include/c++/5/bits/basic_string.h:398:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const basic_string& __str)
       ^
/usr/include/c++/5/bits/basic_string.h:390:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const _Alloc& __a)
       ^
`

**Comment by RElesgoe** [comment]
@d333s try pulling the latest commits and recompiling now.

**Comment by d333s** [comment]
Ok, so I compiled and ran the latest develop commit. No issues while compiling and the crash is fixed too. Still shows the debug logs metioned by @bmunger.

**Comment by bmunger** [comment]
I can also confirm the develop branch fixes the crash.  Thanks everyone!
