### ISSUE TITLE
Some player when game finish will auto logout pvpgn.

### ISSUE THREAD

**Issue by Fatorin** [pvpgn/pvpgn-server#456]
When player finish a game , they will auto logout pvpgn.

Player need re-login pvpgn to join next game.

How can I need change which setting to avoid this problem?

**Comment by RElesgoe** [comment]
Which game? Is there a way to reliably reproduce this problem?
Maybe the player has an unreliable connection to your server.

**Comment by Fatorin** [comment]
When play Warcraft III, custom game.
When they finish the game and return to the lobby, they will receive a disconnect message.
Some players have this problem every time.

**Comment by RElesgoe** [comment]
Are there any client side modifications?
Do the logs indicate a reason why they were disconnected?

There's no indication that this is a pvpgn problem.

**Comment by Fatorin** [comment]
The error message in the server log only shows the following.
[error] topiclist_save: topic conf not loaded

But it should have nothing to do with this, I only see the logout message displayed normally.

Client is from w3l_1_5_1_1_by_Keres.zip, not modify.

**Comment by RElesgoe** [comment]
I suggest compiling the code from the `develop` branch.

I don't think I can help with this problem, I doubt it's a pvpgn issue.

**Comment by Fatorin** [comment]
OK, I will build new version from the develop branch.
And open the trace and debug in the log options to check the reason.

Thanks for your reply!

**Comment by cen1** [comment]
This is not pvpgn issue, it is the W3 client failing to send null packets to keep the connection alive, usually due to network problems.

**Comment by Fatorin** [comment]
Thank you talking to me about this information, I thought it was a pvpgn problem. But it's actually the player's network problem.

**Comment by Strongis13** [comment]
I am also having this issue, but I don't think it is caused by the clients. I am running pvpgn on Linux using latest commits from develop branch, and after every game about half of the players get disconnected and need to log back in to battle.net. When I ran the server on Windows this issue did not happen, which is why I think it may not be the client's fault. Could there be something else on my server's config/network side causing the issue? I have tried adjusting `nullmsg` and `use_keepalive` options in bnetd.conf but nothing has helped so far.
